version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: PasswordManager.Api/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=PasswordManager;User=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development

  web:
    build:
      context: .
      dockerfile: PasswordManager.Web/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - api

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

volumes:
  sqldata: 